[build]
  # No build command needed for static site
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect API calls to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["public"], Country = ["!*"]}

[functions]
  directory = "netlify/functions"